# Generated by Django 4.0.2 on 2022-07-11 20:43

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300)),
                ('nota', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('tema', models.CharField(blank=True, default='All', max_length=45, null=True)),
                ('area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Ciencias'), ('B', 'Biologia'), ('S', 'Sociedade'), ('E', 'Engenharias'), ('L', 'Linguística'), ('P', 'Política'), ('P', 'História')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Ciencias'), ('B', 'Biologia'), ('S', 'Sociedade'), ('E', 'Engenharias'), ('L', 'Linguística'), ('P', 'Política'), ('H', 'História')], max_length=20)),
                ('tema', models.CharField(max_length=45)),
                ('conteudo', models.TextField(max_length=15000)),
                ('descricao', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
