# Generated by Django 4.0.2 on 2022-07-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RedifApp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='avaliacoes',
            field=models.ManyToManyField(related_name='redacoesAvaliadas', through='RedifApp.Avaliacao', to='accounts.Usuario'),
        ),
        migrations.AddField(
            model_name='redacao',
            name='fk_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redacao', to='accounts.usuario'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Filtros', to='accounts.usuario'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='redacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='RedifApp.redacao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='accounts.usuario'),
        ),
    ]
